### ISSUE TITLE
Widok profilu użytkownika

### ISSUE THREAD

**Issue by DontEatRice** [DontEatRice/BookBook#130]
Widok jest zaplanowany mniej więcej w FIGMIE!!!!!!!
https://www.figma.com/file/hPSxZl8Y0A4sH4ZwwV0kWT/Prototyp?type=design&node-id=0-1&mode=design&t=xQkj6s1X6jn5VdGd-0

**Comment by michaljn2** [comment]
Myślę, że można też dodać tu coś w stylu 'Ostatnie zarezerwowane ksiązki przez użytkownika'
