### ISSUE TITLE
Krytyk - implementacja

### ISSUE THREAD

**Issue by DontEatRice** [DontEatRice/BookBook#166]
No to tak, 

- potrzebujemy rozróżniać opinie krytyków od opinii normików 
- w profilu użytkownika, powinna być jakaś labelka informująca o tym, że jest to krytyk
- oddzielny rating w rankingu, po którym można by sortować
- jakaś funkcja dla admina, żeby zmieniać użytkowników w krytyków

**Comment by michaljn2** [comment]
Przy okazji dodam datę utworzenia konta użytkownika (w profilu niech się wyświetla np. użytkownik od marzec 2022)
