### ISSUE TITLE
Testy - Śledztwo

### ISSUE THREAD

**Issue by DontEatRice** [DontEatRice/BookBook#173]
Jak je robimy, unti czy e2e? Może trzeba Bajszczaka spytać? 
Fajnie jakbyście @jgulinski i @michaljn2 zobaczyli jak u was w pracy się to robi bo u mnie się nie piszę testów xd

**Comment by jgulinski** [comment]
U mnie zwykle unit + integracyjne w monolitach, wg mnie najlepiej będzie otestować jakieś 2 czy 3 najbardziej skomplikowane scenariusze typu wypożyczenie bo crudów to nie ma co testować
