### ISSUE TITLE
Wyszukiwanie (search bar w headerze) - obgadać jak chcemy to zrobić (problem ze spójnością inputów w dwóch search barach)

### ISSUE THREAD

**Issue by michaljn2** [DontEatRice/BookBook#188]

**Comment by DontEatRice** [comment]
Imo to powinno wyglądać tak:
Zmniejszyć ten search bar na górze (w kontekście #189) i tak jak mówiłeś, wyszukiwanie na enter albo kliknięcie lupki (musi być coś do kliknięcia bo mobilki)
wywalić wyszukiwanie na stronie książek

Dla przykładu jak to jest zrobione w takim morele
![image](https://github.com/DontEatRice/BookBook/assets/49558286/5250d260-d563-48fa-9584-1d744fafcbd2)

**Comment by michaljn2** [comment]
@DontEatRice tylko czy to wtedy będzie spójne z Autorami? bo tam znowu mamy search bar. 
No ale ogólnie to fakt, najłatwiej wywalić jeden search bar. Ja wczoraj trochę siedziałem i ciężko to ogarnąć, żeby było zawsze to samo w jednym i drugim i w URLu

**Comment by michaljn2** [comment]
Ta, to wiem. To wywalę ten w książkach
