### ISSUE TITLE
Access Token Generation Bug

### ISSUE THREAD

**Issue by DontEatRice** [DontEatRice/BookBook#55]
![image](https://github.com/DontEatRice/BookBook/assets/49558286/83c4ea5b-3f55-4a93-8512-b7c090539065)

Expires jest brane z `AuthConstants.RefreshTokenDuration` zamiast z parametru `expires`.

Dodatkowo może zamiast 
```csharp
public string GenerateAccessToken(Guid identityId, string email, Role role = Role.User)
{
   return GenerateToken(identityId, email, AuthConstants.AccessTokenDuration, role);
}
```

po prostu generujmy jakiś losowy ciąg znaków? Normalnie korzystam z czegoś takiego:
```csharp
public static string GenerateRefreshToken()
{
        var guidBytes = Guid.NewGuid().ToByteArray();
        var hashBytes = SHA256.HashData(guidBytes);
        return Convert.ToBase64String(hashBytes);
}
```
czyli hashowanie losowego Guida

**Comment by jgulinski** [comment]
Expires rzeczywiście przeoczenie. A co do generowania tokenu to nie wiem czy czaję o co Ci chodzi. Zamiast generowania jwt tokena ze wszystkim claimami chcesz zwracać hashowany guid czy czegoś nie czaje?

**Comment by DontEatRice** [comment]
@jgulinski Źle wkleiłem sry, chodzi mi o refresh token, nie wiem w jakim celu ma to być jwt tak właściwie i gdzie nam się to przyda

**Comment by jgulinski** [comment]
U nas to raczej jedynie ten czas wygaśnięcia dla refresh tokenu, jeżeli to coś uprości to można dać twoje rozwiązanie myślę
